name: Archive zip file for Wordpress installation

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Zip Release
        uses: TheDoctor0/zip-release@0.7.1
        with:
          # Filename for archive
          filename: malakat-pay-for-woocommerce.zip
          # List of excluded files / directories
          exclusions: "*.git* *.github*"

      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "malakat-pay-for-woocommerce-${{ github.ref_name }}.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
